### ISSUE TITLE
ng2-overlay imports BrowserModule, should import CommonModule

### ISSUE THREAD

**Issue by dozer75** [ng2-ui/overlay#1]
The ng2-overlay component imports BrowserModule, this causes code that is built upon lazy loaded modules to fail with the following message:

> EXCEPTION: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

The import of the BrowserModule should be the responsibility to the base loader and not be done in a component like this. Please use CommonModule instead.

**Comment by dozer75** [comment]
Added a Pull Request for this #2

**Comment by allenhwkim** [comment]
Thank you

**Comment by dozer75** [comment]
Nice, I hope an updated NPM package is on it's way to.

**Comment by allenhwkim** [comment]
published as v0.6.3
