### ISSUE TITLE
Support for Angular 4.0.0

### ISSUE THREAD

**Issue by karllhughes** [ng2-ui/overlay#4]
I just tried to install on Angular 4 today and got this error:

```
frontend
├── UNMET PEER DEPENDENCY @angular/common@4.0.1
├── UNMET PEER DEPENDENCY @angular/core@4.0.1
└─┬ overlay@1.2.5 
  └── q@0.9.6 

npm WARN angular2-modal@2.0.3 requires a peer of @angular/core@^2.1.1 but none was installed.
npm WARN angular2-modal@2.0.3 requires a peer of @angular/common@^2.1.1 but none was installed.
```

Any chance Angular 4.0.0 support is coming? I don't know much about how this library works, but I can try to dig in later this week and test it out if that's helpful.

**Comment by allenhwkim** [comment]
There is no dependency for Angular as you see.

https://github.com/ng2-ui/overlay/blob/master/package.json#L28.

**Comment by karllhughes** [comment]
My mistake. Not sure why I was getting that error. Must have been another package hadn't updated properly.

Thanks!
